steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/uctalent-repo/playwright-test:$COMMIT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/uctalent-repo/playwright-test:latest',
      '.'
    ]
    dir: 'playwright-tests'

  # 2. Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/uctalent-repo/playwright-test', '--all-tags']
